/*
 * Description: CIS 254 Lab 2 - Similar to the ELIZA program, this program ask how the user is feeling and returns
 * a response based on the input.
 * Group: 12
 * Authors: Henry Penas, Eric Orea
 */

import java.util.Scanner;
import java.util.Random;

public class Lab2 {
    
    private static final String THERAPIST = "Dr. Giggles";

    private static final String[] sentences = {
        "How does that make you feel?",
        "Tell me more about that.",
        "What do you think about that?",
        "Why do you say that?",
        "Can you explain that further?"
    };

    /**
     * Displays a welcome message
     */
    public static void welcome() {
        System.out.println("Welcome to " + THERAPIST + "'s therapy session. How are you feeling today? (Happy, Sad, Tired, Anxious)");
    }
  
    /**
     * Generates a random response from the array above
     * @param userInput - The user's input
     * @return Selects Random sentence from the list above
     */
    public static String generateResponse(String userInput) {
        Random rand = new Random();
        int index = rand.nextInt(sentences.length);
        return sentences[index];
    }
    
    /**
     * Processes the user's input and returns a response
     * @param userInput - The user's input
     * @return Response generated by the Therapist
     */
    public static String processInput(String userInput) {
        String response = generateResponse(userInput);
        return response;
    }
    
    /**
     * main method that continues the loop until "goodbye" has been inputed
     * which will end the program
     */
    public static void main(String[] args) {
        welcome();
        Scanner scanner = new Scanner(System.in);
        String input;
        do {
            input = scanner.nextLine();
            System.out.println(getResponse(input));
        } while (!input.equalsIgnoreCase("Goodbye"));
        System.out.println("Goodbye. Take care!");
        scanner.close();
    }
    
    
    /**
     * Generates response based on keywords
     * @param input - the user's input
     * @return Response generated by the Therapist
     */
    public static String getResponse(String input) {
        String[] words = input.split("\\s+");
        String lastWord = words[words.length - 1];
        
        if (lastWord.equalsIgnoreCase("sad")) {
            return "I'm sorry to hear that. What's been making you feel sad?";
        } else if (lastWord.equalsIgnoreCase("happy")) {
            return "That's great to hear that you're happy! What's been going well for you lately?";
        } else if (lastWord.equalsIgnoreCase("tired")) {
            return "Why do you think you're feeling tired?";
        } else if (lastWord.equalsIgnoreCase("anxious")) {
            return "I'm sorry to hear that you're feeling anxious. Can you tell me more about what's been causing your anxiety?";
        } else if (input.equalsIgnoreCase("Goodbye")) {
            return "";
        } else {
            return sentences[(int)(Math.random() * sentences.length)];
        }
    }
}
